services:
  sentiment-frontend:
    build: ./FrontEnd
    container_name: sentiment-frontend
    networks:
      - sentiment-net

  sentiment-backend:
    build: ./BackEnd
    container_name: sentiment-backend
    environment:
      - SENTIMENT_MODE=python
      - PYTHON_API_BASE_URL=http://sentiment-model:8000
    depends_on:
      - sentiment-model
    networks:
      - sentiment-net

  sentiment-model:
    build: ./FastAPI
    container_name: sentiment-model
    ports:
      - "8000:8000"
    networks:
      - sentiment-net

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - sentiment-frontend
      - sentiment-backend
    networks:
      - sentiment-net

networks:
  sentiment-net:
    driver: bridge
