services:
  sentiment-frontend:
    build: ./FrontEnd
    container_name: sentiment-frontend
    ports:
      - "4200:80"
    networks:
      - sentiment-net

  sentiment-backend:
    build: ./BackEnd
    container_name: sentiment-backend
    ports:
      - "8080:8080"
    environment:
      - SENTIMENT_MODE=python
      - PYTHON_API_BASE_URL=http://sentiment-model:8000
      - SPRING_DATASOURCE_URL=jdbc:h2:file:./data/sentimentdb
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_ERROR_INCLUDE_MESSAGE=always
      - SERVER_ERROR_INCLUDE_BINDING_ERRORS=always
      - SERVER_ERROR_INCLUDE_STACKTRACE=always
      - SPRING_JACKSON_SERIALIZATION_FAIL_ON_EMPTY_BEANS=false
    depends_on:
      - sentiment-model
    networks:
      - sentiment-net

  sentiment-model:
    build: ./FastAPI
    container_name: sentiment-model
    ports:
      - "8000:8000"
    networks:
      - sentiment-net

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - sentiment-frontend
      - sentiment-backend
    networks:
      - sentiment-net

networks:
  sentiment-net:
    driver: bridge
